### ISSUE TITLE
noVNC not working 

### ISSUE THREAD

**Issue by pavitaeka** [biplobsd/OneClickRun#14]
![image](https://user-images.githubusercontent.com/72183763/102227011-a6339f80-3f1b-11eb-892c-a30e8da50b25.png)

> Failed to complete tunnel connection
The connection to http://9af8e020a6aa.au.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:6080.
Make sure that a web service is running on localhost:6080 and that it is a valid address.
The error encountered was: dial tcp 127.0.0.1:6080: connect: connection refused

**Comment by biplobsd** [comment]
It's working fine!. 

Runtime>Factory reset runtime
![image](https://user-images.githubusercontent.com/43641536/102472707-c29d1c80-4080-11eb-935c-5eb59eeb0ef1.png)

Then try again!
