### ISSUE TITLE
Problem with aria2Rpc 

### ISSUE THREAD

**Issue by littlesudip** [biplobsd/OneClickRun#2]
When I'm trying to run aria2Rpc On LocalHost. Its shows this error **https://prnt.sc/spkwcj.**
but with ngrok aria2Rpc runs successfully.but if i downloaded a torrent video file with aria2Rpc on my drive.then I downloaded that video file on my computer. showhow that video gets corrupted or damaged. like this **https://prnt.sc/spky7r**
 but there no problem with my download manager. so i think that's a problem with aria2R.
so how can i fix this issue?

**Comment by biplobsd** [comment]
Reset your browser dns cashe or try again later. And 2nd problem, Maybe your connection broken! When download any file from colab, try to copy file to gdrive or just open filebrowser and then download!
