### ISSUE TITLE
Jellyfin error

### ISSUE THREAD

**Issue by thecharlie654** [biplobsd/OneClickRun#26]
I get the following error when trying to run Jellyfin.
![Screenshot_20220105-232212~2](https://user-images.githubusercontent.com/49923828/148304022-195f6afb-ef57-4415-a9e5-bb0865b924a8.png)

**Comment by biplobsd** [comment]
896a809e1e3add07d2973a5bfa42a3bc8ae6cbf6 Fixed

Thanks for your reporting.
