### ISSUE TITLE
[REQ]Zippyshare Upload

### ISSUE THREAD

**Issue by fruitpunchsamurai2** [biplobsd/OneClickRun#27]
@biplobsd  Can you please make zippyshare remote uploader like anon & bayfiles. It would really be useful i think, one already available [Here](https://colab.research.google.com/github/cheems/Remote-Uploader/blob/main/Remote_Uploader.ipynb#scrollTo=XkzrDIs_CMyO)  But don't work sadly, not able to find any other working one.
Thanks For Notebook btw great tools you've put together 🙂👌

**Comment by bunnykek** [comment]
https://github.com/biplobsd/OneClickRun/pull/35
MultiUpload can do this
