### ISSUE TITLE
code-server x86_64 installation file not found!

### ISSUE THREAD

**Issue by biplobsd** [biplobsd/OneClickRun#37]
Just remove X86_64 from PACKAGES and set default amd64. You can find on code-server cell.
![image](https://user-images.githubusercontent.com/43641536/193443103-8fbf82ea-0848-4bfc-b726-71fd6e6f0718.png)
Then just create a pull request and referring this issues tag number #... .

**Comment by Indrajeet-S** [comment]
@biplobsd I would like to make this change.. could you assign this to me

**Comment by Indrajeet-S** [comment]
@biplobsd

**Comment by biplobsd** [comment]
> @biplobsd

@Indrajeet-S Sure. All of issue is open to pick anyone. It is good if yourself assign. It is help other contributors to know this issue is working.

**Comment by Indrajeet-S** [comment]
@biplobsd, I made the change
Could you please review and let me know
