### ISSUE TITLE
Firefox not opening on noVnc

### ISSUE THREAD

**Issue by biplobsd** [biplobsd/OneClickRun#44]
First reported on OneClickRun telegram group from Ab.

## Discussion screenshot
![image](https://github.com/biplobsd/OneClickRun/assets/43641536/69a2a82b-7950-4685-8875-ad0ecd968172)

**Comment by LimitBreaker01** [comment]
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
dpkg -i google-chrome-stable_current_amd64.deb
apt-get install -f
google-chrome-stable --user-data-dir --no-sandbox

https://unix.stackexchange.com/questions/175967/how-to-run-google-chrome-as-root-in-linux

google chrome good

**Comment by biplobsd** [comment]
@LimitBreaker01 great. Can you make a pull request for this change.. Also can you add the firefox?
