### ISSUE TITLE
wetty Function failure

### ISSUE THREAD

**Issue by LimitBreaker01** [biplobsd/OneClickRun#52]
wetty 
PORT_FORWARD: argotunnel
The generated link cannot be opened
<img width="466" alt="2023-10-09_101315" src="https://github.com/biplobsd/OneClickRun/assets/65392605/aee02bec-4507-4625-a7ce-3c0fc0207740">
<img width="958" alt="2023-10-09_101334" src="https://github.com/biplobsd/OneClickRun/assets/65392605/d03e356c-e5e6-4cc4-a874-15d75d039d85">

**Comment by biplobsd** [comment]
If anyone wants to work on this issue, he is always welcome.

**Comment by LimitBreaker01** [comment]
> 你好@LimitBreaker01，https://colab.research.google.com/github/biplobsd/OneClickRun/blob/52-wetty-function-failure/OneClickRun.ipynb
> 
> 试试这款笔记本。我已经更新了wetty版本2.7.0。

Thank you so much
