### ISSUE TITLE
Create a pull request template file

### ISSUE THREAD

**Issue by biplobsd** [biplobsd/OneClickRun#57]
The pull request template includes - 
- Summary
  - Fixes issues hash number
- Category
- Screenshots or GIFs (if applicable)
- Additional Information (optional)

How to create a pull request template? 
check out: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by carlospatinos** [comment]
Happy to take this one, can I help please? Just assign it to me

**Comment by biplobsd** [comment]
Yes.. Assigned @carlospatinos

**Comment by AnirbanBall** [comment]
Can you assign this to me .Happy to contribute

**Comment by carlospatinos** [comment]
Sorry just finished this myself

**Comment by biplobsd** [comment]
@AnirbanBall check other issues. Might be good first issues 😊

**Comment by AnirbanBall** [comment]
Okey thanks dear
