### ISSUE TITLE
Remove Anonfiles cells

### ISSUE THREAD

**Issue by biplobsd** [biplobsd/OneClickRun#58]
`transferTools/Anonfiles`
![image](https://github.com/biplobsd/OneClickRun/assets/43641536/c4bfee79-3a27-4fe8-a1b1-b328fec56ab1)

## Steps
- Upload logo into /img directory 
- Replace logo url

**Comment by avi-dey** [comment]
I am picking this up

**Comment by biplobsd** [comment]
Sure, Assigned @avi-dey

**Comment by avi-dey** [comment]
@biplobsd anonfiles have officially closed their service forever. I checked the code, it is of no use now. So, the logo also serves no purpose. What do you want me to do?
some sources that support my claim:
[beepingcomputer](https://www.bleepingcomputer.com/news/security/file-sharing-site-anonfiles-shuts-down-due-to-overwhelming-abuse/)
[reddit](https://www.reddit.com/r/privacy/comments/15oiqwr/did_anon_files_shut_down/)
[socradar](https://socradar.io/anonfiles-forced-to-shut-down-due-to-surge-of-malicious-utilization/)

**Comment by biplobsd** [comment]
Can you delete that cell from notebook?

**Comment by avi-dey** [comment]
@biplobsd do you want me to delete all entries where you have claimed support for Anonfiles? I will also reorder the files accordingly.
Here's an example. I will delete Anonfiles entry and fix the numbering. 
![Screenshot from 2023-10-14 21-01-00](https://github.com/biplobsd/OneClickRun/assets/97702087/91ee8105-e310-4cf0-8f48-2ef7727d60eb)

**Comment by biplobsd** [comment]
![image](https://github.com/biplobsd/OneClickRun/assets/43641536/6e368c0b-55f0-406a-bb25-c67823da1921)
![image](https://github.com/biplobsd/OneClickRun/assets/43641536/2f673a7f-2511-4942-9d0d-5eb7034bfd94)
![image](https://github.com/biplobsd/OneClickRun/assets/43641536/cd03afaa-bc51-4747-8f90-334925c305e5)
![image](https://github.com/biplobsd/OneClickRun/assets/43641536/1179cf31-ca9f-4d18-b228-582eb0e05de7)


Finally, make sure all cells are collapse properly.

**Comment by avi-dey** [comment]
is there any reason why this project does not have a requirements.txt or some equivalent file to install all libraries at once?
it's difficult to run the notebook as I have to install the libraries manually, which takes up a lot of time.

**Comment by biplobsd** [comment]
@avi-dey  You don't want to setup this in your locally. (I will create a issue for refer this step to contribution)
Here I do changes in Notebook.

Step:
- Fork this repository
- Go to README.md and Open in colab
- Do your changes
- For commit: File> Save a copy in Github. Select your fork OneClickRun repository.
![image](https://github.com/biplobsd/OneClickRun/assets/43641536/2172d677-e1cd-4b3d-9584-17b2691dc365)

Let me ask again if you haven't understand on any step

**Comment by avi-dey** [comment]
thanks for guiding me. I didn't knew about this feature in colab :)
