### ISSUE TITLE
Update L3MON logo

### ISSUE THREAD

**Issue by biplobsd** [biplobsd/OneClickRun#60]
`pentester/L3MON DEMO`
![image](https://github.com/biplobsd/OneClickRun/assets/43641536/a66a1907-148f-411b-ac29-a77a4bb38c8f)

## Steps
- Upload logo into /img directory 
- Replace logo url

**Comment by Ritish134** [comment]
Hi there excited to contribute can you assign me this issue

**Comment by biplobsd** [comment]
Assigned @Ritish134

**Comment by biplobsd** [comment]
@Ritish134 any updates?

**Comment by Ritish134** [comment]
Yup its done .. created a PR#67
