### ISSUE TITLE
Suggestion : improvement in README.md (inside  section - "Contributing to OneClickRun" ) 

### ISSUE THREAD

**Issue by ayushrakesh** [biplobsd/OneClickRun#69]
Inside section "Contributing to OneClickRun" in README.md file.  First line starts with "Got a unique idea .." , I suggest to change it like below 👇.

"Do you have a unique idea.."     What say? I think now it sounds beautiful.

![Screenshot (74)](https://github.com/biplobsd/OneClickRun/assets/115995339/5d778663-618d-4a00-9a07-f5ae2493c383)

Please assign this issue to me.

**Comment by biplobsd** [comment]
Great, @ayushrakesh assigned
