### ISSUE TITLE
Enhancing code readability

### ISSUE THREAD

**Issue by DhanushNehru** [biplobsd/OneClickRun#76]

**Comment by biplobsd** [comment]
Hey @DhanushNehru STOP THIS. We don't need any code readability enhancement. Our focus is on better performance, efficient. You pr is not adding any value to our `OneClickRun` right now. You should focus on adding new features or fix any broken cell. 

Please describe your ideas in the issue description box. After that, I will review your ideas and check if there are any invalids. Then, create a pull request (PR).
