### ISSUE TITLE
Jellyfin is not working

### ISSUE THREAD

**Issue by omdev420** [biplobsd/OneClickRun#8]
I  was using the lastest colab link to start a jellyfin session but it crashed with this error:
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-1-e997ded7f184> in <module>()
     66   outputFile = 'tools/jellyfin/temp/jellyfin.tar.gz'
     67 
---> 68   urllib.request.urlretrieve(dlLink, outputFile)
     69   with tarfile.open(outputFile, 'r:gz') as tar_ref:
     70       tar_ref.extractall('tools/jellyfin')

6 frames
/usr/lib/python3.6/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    648 class HTTPDefaultErrorHandler(BaseHandler):
    649     def http_error_default(self, req, fp, code, msg, hdrs):
--> 650         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    651 
    652 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 404: Not Found

**Comment by biplobsd** [comment]
ac967596b2c019ad4a3906c0408c5521a913b7d1 Fixed!
